### ISSUE TITLE
op = tests.keys()[0] TypeError: 'dict_keys' object is not subscriptable

### ISSUE THREAD

**Issue by jmondaud** [nadirizr/json-logic-py#14]
I have this issure : 
**op = tests.keys()[0] TypeError: 'dict_keys' object is not subscriptable**

So i change __init__.py at line 14.

`op = tests.keys()[0]`

with :

```
  for key in tests:
    op = key
    break
```
Is there a better way to avoid this error?

regards

**Comment by nathando** [comment]
@jmondaud look at the code, i think the bug has been fixed, but the version in pypi is not the latest. Just download the py file directly from here.

**Comment by jmondaud** [comment]
@nathando yes, that was not the latest, thank you. Works fine now !

**Comment by BananaEgg** [comment]
Seems that this hasn't been updated yet....

**Comment by TheRedWizard** [comment]
still failing
